#Specifies the active directory. The directory must have a translations file, template file and optional .pdf file.
ACTIVE_DIR: invoice 2
#XML template file you want to generate localized copies of.
XML_TEMPLATE_FILE: BC online - PEPPOL3 - Purchase Invoice 2 - Nod Publishers.xml
#Word template file you want to embed in the XML file.
WORD_TEMPLATE_FILE:
#Variables file that contain translations of localized words for the .xml file. Must be a .xlsx file.
XML_VARIABLES_FILE: translations.xlsx
#Variables file that contain translations of localized words for the .docx file. Must be a .xlsx file.
WORD_VARIABLES_FILE: translations.xlsx
